# Generated by Django 4.2.8 on 2025-01-28 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinOutRegion',
            fields=[
                ('attendance_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('organization', models.CharField(max_length=100)),
                ('CHECKTIME', models.DateTimeField()),
                ('CHECKTYPE', models.CharField(max_length=1)),
                ('VERIFYCODE', models.IntegerField()),
                ('SENSORID', models.IntegerField()),
                ('Memoinfo', models.CharField(blank=True, max_length=255, null=True)),
                ('WorkCode', models.IntegerField(blank=True, null=True)),
                ('sn', models.CharField(blank=True, max_length=50, null=True)),
                ('UserExtFmt', models.IntegerField(blank=True, null=True)),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'CHECKTIME'], name='checkinoutR_organiz_1a55af_idx'), models.Index(fields=['USERID', 'organization'], name='checkinoutR_USERID__906ca7_idx')],
            },
        ),
    ]
