# Generated by Django 4.2.16 on 2024-10-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_birthday_useraccount_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
