# Generated by Django 4.2.16 on 2024-10-22 01:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_useraccount_deptid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
