# Generated by Django 4.2.16 on 2024-10-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_useraccount_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='photos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
