# Generated by Django 4.2.8 on 2024-10-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='period',
            field=models.IntegerField(default=1),
        ),
    ]
