# Generated by Django 4.2.16 on 2024-10-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkinout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkinout',
            old_name='USERID',
            new_name='UID',
        ),
    ]
