# Generated by Django 4.2.16 on 2024-10-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('dept_name', models.CharField(blank=True, max_length=100, unique=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
